---
title: Caticorn
author: Caticorn
email: hi@caticorn.cc
description: hello  world
baseurl: "/ubuild-jekyll"
url: www.caticorn.cc
defaults:
- scope:
    path: ''
  values:
    layout: default
markdown: kramdown
gems:
- jekyll-feed
- jekyll-menus
